### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Meta-AI-learner** [deepgogogo/CAGNet#2]
It would be great if you could publish your code for training!

I use the following setting to train on tvhi dataset, but get 87.4/88.9 on F1/ACC, would you tell me what's wrong with it, or any tricks you used? I also try to use the action_weight and inter_weight, but get the similar results. In addition, what's pretrained model?
![H4`8YOJ1PVT2QLAGD`LKEHS](https://user-images.githubusercontent.com/44023016/160231761-30ce196b-5e2d-4df7-acfc-bc1104f0756a.png)
Thanks!

**Comment by deepgogogo** [comment]
Well, thanks for your interests in our work! Training code will be released later. Currently we are working on some improvements of the network. I don't know how you initialize the backbone model. In our exp settings, we first train a basemodel and then use it to initialize the backbone of CAGNet and fix the weight of backbone. Expirically, it gives better performance.

**Comment by meng-jiajun** [comment]
Training code on BIT dataset is released with a pretrained basemodel.
